language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js: stable
before_script:
  - npm install -g bower polymer-cli@next web-component-tester
  - npm install
  - bower install
 script:
  - polymer build --add-service-worker
notifications:
  email: false
