language: node_js
sudo: required
node_js: 8.1
dist: trusty

addons: 
  firefox: latest
  chrome: stable

cache:
  directories:
  - node_modules    
  - bower_components

install: 
- npm install -g yarn
- yarn add global bower
- yarn add global polymer-cli
- node -v
- polymer --version
- yarn --version
- yarn install
- bower install

before_script:
- polymer lint --input ./src/**/*.html
- xvfb-run -s '-screen 0 1024x768x24' wct

script:
- polymer build --verbose
- "if [[ \"$TRAVIS_EVENT_TYPE\" != \"pull_request\" && \"$TRAVIS_BRANCH\" != quick/* ]]; then wct --env saucelabs; fi",
  "if [ \"$TRAVIS_EVENT_TYPE\" = \"cron\" ]; then wct --env saucelabs-cron; fi"

notifications:
  email: false

