language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '7'
  - '6'
before_script:
  - npm install -g bower 
  - npm install -g polymer-cli 
  - npm install -g web-component-tester 
  - npm install -g firebase-tool
  - npm install
  - bower install
  - polymer build --add-service-worker
script:
  - polymer serve
