language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - 'node'
  - '7'
  - '6'
before_script:
  - npm install -g bower polymer-cli web-component-tester firebase-tool
  - npm install
  - bower install
  - polymer build --add-service-worker
script:
  - polymer serve
