language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
  - '7'
before_script:
  - npm install -g bower polymer-cli
  - bower install
  - npm build --add-service-worker
script:
  - xvfb-run npm test
