# Test against this version of Node.js
environment:
  nodejs_version: "8"

version: 1.0.{build}

branches:
  # whitelist
  only:
    - master
    - production

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

# build cache to preserve files/folders between builds
cache:
  - node_modules                    # local npm modules

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # Get the latest stable version of npm 
  - yarn add global bower
  - yarn add global polymer-cli 
 # install modules. Use --force to workaround permissions issues on Windows
  - yarn install
  - bower install
  
# scripts to run before build
before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - polymer --version
  - yarn --version

# to run your custom scripts instead of automatic MSBuild
build_script:
  - polymer build --verbose

# Post-install test scripts.
test_script:
  - polymer lint

# Don't actually build.
build: off
